version: 1.0.{build}
image: Visual Studio 2017

configuration:
  - DebugStatic
  - ReleaseStatic

platform: Win64

init:
  - cmd: ''

before_build:
  - cmd: external\premake5.exe --scripts=premake/ --install-prefix=install/ vs2017

build:
  project: build\caramel-poly.sln
  verbosity: minimal
  
test_script:
  - cmd: |
     @echo %env.configuration%_%env.platform%
     @echo ================= RUNNING TESTS =================
     build\%env.configuration%_%env.platform%\bin\caramel-poly-test.exe
     @echo ============== RUNNING BENCHMARKS ===============
     build\%env.configuration%_%env.platform%\bin\caramel-poly-benchmark.exe
